spring.application.name=authentication-service
server.port=${SERVER_PORT:8080}

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_service_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.data.jpa.repositories.enabled=true
spring.jpa.open-in-view=false

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=3600000
jwt.refresh-expiration=604800000

logging.level.com.inno.task.authentication_service=DEBUG
logging.level.org.springframework.security=DEBUG